apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-ingress-controlplane-class
  annotations:
    policies.kyverno.io/title: Restrict IngressClass Controlplane
    policies.kyverno.io/category: Internal Logic
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Inress rule with this IngressClass accessible via ProdUI VPN.
      Cloud Engeneeirng want to control this IngressClass and restrict it to specific namespaces 
spec:
  background: false
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 20
  rules:
    - name: deny-restricted-ingress-class
      match:
        resources:
          kinds:
            - Ingress
      validate:
        message: >-
          [E017] The IngressClass 'nginx-controlplane' is restricted and cannot be used in the namespace {{`'{{request.namespace}}'`}}
          (details: my-url/Kyverno+rules#Kyvernorules-[E017]TheIngressClass'nginx-controlplane'isrestrictedandcannotbeusedinthenamespace)
        deny:
          conditions:
            - key: "{{`{{ request.object.spec.ingressClassName }}`}}"
              operator: Equals
              value: "nginx-controlplane"
            - key: "{{`{{ request.namespace }}`}}"
              operator: NotIn
              value: ["kubecost", "argo-workflows"]

