apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-ingress-tls
  annotations:
    policies.kyverno.io/title: Require Ingress TLS
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Ingress resources should only allow secure traffic. 
      This policy requires that all Ingress resources specify TLS in the spec.      
spec:
  background: true
  validationFailureAction: audit
  rules:
  - name: has-tls
    match:
      any:
      - resources:
          kinds:
          - Ingress
    preconditions:
      all:
      - key: "{{`{{request.operation || 'BACKGROUND'}}`}}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
    validate:
      message: "TLS must be defined."
      deny:
        conditions:
          all:
          - key: tls
            operator: AnyNotIn
            value: "{{`{{ request.object.spec.keys(@) }}`}}"
